#!/usr/bin/env bash
# This script kills the 7-highlander process

# Use pgrep to find the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

if [ -n "$PID" ]; then
    kill -SIGTERM "$PID"
else
    echo "No 7-highlander process found."
fi

