#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely,
# and shows "I am invincible!!!" when receiving a SIGTERM signal

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap the SIGTERM signal and call the handler function
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

