#!/usr/bin/env bash
# Set the Internal Field Separator to newline and colon
IFS=$'\n'

# Read the /etc/passwd file line by line
while read -r line; do
	# Split the line into fields using IFS
	USERNAME=$(echo "$line" | cut -d':' -f1)
	GROUP_ID=$(echo "$line" | cut -d':' -f4)
	HOME_DIRECTORY=$(echo "$line" | cut -d':' -f6)
	COMMAND_SHELL=$(echo "$line" | cut -d':' -f7)
	PASSWORD=$(echo "$line" | cut -d':' -f2)
	USER_ID_INFO=$(echo "$line" | cut -d':' -f5)

	# Display the formatted output
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $GROUP_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd

